# Site settings
title: "Ampersands Are Lovely"
email: adrianjonmiller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring the wonderful world of ampersands one font at a time
baseurl: "/ampersand" # the subpath of your site, e.g. /blog/
url: "http://adrianjmiller.me" # the base hostname & protocol for your site
twitter_username: adrianjonmiller
github_username:  adrianjonmiller

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Build settings
markdown: kramdown
